import Head from 'next/head'
import Image from 'next/image'
import Form from '../components/Form'

export default function Home() {
  return (
    <div className="h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='h-full flex items-center justify-center'>
        <Form/>
      </div>

      
    </div>
  )
}
